// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://narvjcteixgjclvjvlbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcnZqY3RlaXhnamNsdmp2bGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxNzMwODQsImV4cCI6MjA4MDc0OTA4NH0.M_-YQYDJqrEKguqwcJwM5mx2PSt1vFRZ0qytaxSlMMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});